#!/usr/bin/env python
from scapy.all import *

def monitor_callback(pkt):
	global counter
	print pkt.show()
	counter += 1
	print counter

counter = 0
sniff(prn=monitor_callback, filter = "arp", store = 0)
